name: "SurfMind"
description: "Instant AI on the Web. SurfMind adds to your browser an AI chat sidebar that understands the page you're on to help you work smarter and faster. Compatible with Chrome, Edge, Safari, Firefox and any Chromium browser."
url: "https://surfmind.ai"
docs: "https://surfmind.ai/blog/how-to-use-openrouter-in-your-browser"
tags:
  - chat
  - productivity
date_added: "2026-08-05"
