name: "Chatbox"
description: "Your Ultimate AI Copilot on the Desktop. Chatbox is a desktop client for ChatGPT, Claude and other LLMs, available on Windows, Mac, Linux, iOS, and Android."
url: "https://chatboxai.app"
docs: "https://chatboxai.app/en/help-center"
tags:
  - chat
  - coding
  - productivity
open_source: "https://github.com/chatboxai/chatbox"
date_added: "2026-01-15"
